### ISSUE TITLE
Does this actually interact with IEX data?

### ISSUE THREAD

**Issue by dknesek** [philcallister/ticker-elixir#1]
I see IEX referenced here and there, but your projects refer to Google Finance instead of IEX (https://iextrading.com/developer).

**Comment by philcallister** [comment]
@dknesek it does if you use the **elixir_1.4_iex** branch. It doesn't work with their socket.io endpoint yet, but it does work with their HTTP. To be honest, I haven't actually tried it for quite some time, so if you give it a try, let me know if you find any issues with it.
